[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ibeat-dixon"
version = "0.0.0"
dependencies = [
  'miblab',
  'miblab-data',
]

[tool.setuptools.packages.find]
where = ["src"]